version: "3.9"

services:

  author-left:
    image: aemdesign/aem:6.5.11.0-jdk11
    hostname: author-left
    healthcheck:
      test: curl -u admin:admin --header Referer:localhost --silent --connect-timeout 5 --max-time 5 http://localhost:8080/system/console/bundles.json | grep -q \"state\":\"Installed\" && exit 1 || exit 0
      interval: 10s
      timeout: 10s
      retries: 200
      start_period: 60s
    environment:
      - AEM_RUNMODE=-Dsling.run.modes=author,crx3,crx3tar,localdev,nosamplecontent,authorleft
      - AEM_JVM_OPTS=-server -Xms248m -Xmx1524m -XX:MaxDirectMemorySize=256M -XX:+CMSClassUnloadingEnabled -Djava.awt.headless=true -Dorg.apache.felix.http.host=0.0.0.0 -Xdebug -Xrunjdwp:transport=dt_socket,server=y,address=58242,suspend=n
    volumes:
      - author-left-data-blobids:/aem/crx-quickstart/repository/blobids
      - author-data-datastore:/aem/crx-quickstart/repository/datastore
      - author-left-data-index:/aem/crx-quickstart/repository/index
      - author-left-data-segmentstore:/aem/crx-quickstart/repository/segmentstore
      - author-data-key:/aem/key
      - ./packages/agents.zip:/aem/crx-quickstart/install/99-agents.zip
    labels:
      # note that you want this frontened to match the last. otherwise it will match login.${HOST_DOMAIN}"
      traefik.frontend.priority: 1
      traefik.enable: true
      traefik.http.routers.author_left.rule: "Host(`author-left.localhost`)"
      traefik.http.routers.author_left.entrypoints: web
      traefik.http.routers.author_left_https.rule: "Host(`author-left.localhost`)"
      traefik.http.routers.author_left_https.tls: true
      traefik.http.routers.author_left_https.entrypoints: websecure
      traefik.http.services.author_left.loadbalancer.passHostHeader: true
    networks:
      - default
      - author-network
      - publish-network
      - dispatcher-network

  author-left-webdav:
    image: aemdesign/java-buildpack:jdk11
    command: curl -u admin:admin -H User-Agent:curl -F "jcr:primaryType=sling:OsgiConfig" -F "alias=/crx/server" -F "dav.create-absolute-uri=true" -F "dav.create-absolute-uri@TypeHint=Boolean" -F"../../jcr:primaryType=sling:Folder" -F"../jcr:primaryType=sling:Folder" http://author-left:8080/apps/system/config/org.apache.sling.jcr.davex.impl.servlets.SlingDavExServlet
    depends_on:
      author-left:
        condition: service_healthy
    networks:
      - default
      - author-network

  author-right:
    image: aemdesign/aem:6.5.11.0-jdk11
    hostname: author-right
    healthcheck:
      test: curl -u admin:admin --header Referer:localhost --silent --connect-timeout 5 --max-time 5 http://localhost:8080/system/console/bundles.json | grep -q \"state\":\"Installed\" && exit 1 || exit 0
      interval: 10s
      timeout: 10s
      retries: 200
      start_period: 60s
    environment:
      - AEM_RUNMODE=-Dsling.run.modes=author,crx3,crx3tar,localdev,nosamplecontent,authorright
      - AEM_JVM_OPTS=-server -Xms248m -Xmx1524m -XX:MaxDirectMemorySize=256M -XX:+CMSClassUnloadingEnabled -Djava.awt.headless=true -Dorg.apache.felix.http.host=0.0.0.0 -Xdebug -Xrunjdwp:transport=dt_socket,server=y,address=58242,suspend=n
    volumes:
      - author-right-data-blobids:/aem/crx-quickstart/repository/blobids
      - author-data-datastore:/aem/crx-quickstart/repository/datastore
      - author-right-data-index:/aem/crx-quickstart/repository/index
      - author-right-data-segmentstore:/aem/crx-quickstart/repository/segmentstore
      - author-data-key:/aem/key
      - ./packages/agents.zip:/aem/crx-quickstart/install/99-agents.zip
    labels:
      # note that you want this frontened to match the last. otherwise it will match login.${HOST_DOMAIN}"
      traefik.frontend.priority: 1
      traefik.enable: true
      traefik.http.routers.author_right.rule: "Host(`author-right.localhost`)"
      traefik.http.routers.author_right.entrypoints: web
      traefik.http.routers.author_right_https.rule: "Host(`author-right.localhost`)"
      traefik.http.routers.author_right_https.tls: true
      traefik.http.routers.author_right_https.entrypoints: websecure
      traefik.http.services.author_right.loadbalancer.passHostHeader: true
    networks:
      - default
      - author-network
      - publish-network
      - dispatcher-network

  author-right-webdav:
    image: aemdesign/java-buildpack:jdk11
    command: curl -u admin:admin -H User-Agent:curl -F "jcr:primaryType=sling:OsgiConfig" -F "alias=/crx/server" -F "dav.create-absolute-uri=true" -F "dav.create-absolute-uri@TypeHint=Boolean" -F"../../jcr:primaryType=sling:Folder" -F"../jcr:primaryType=sling:Folder" http://author-right:8080/apps/system/config/org.apache.sling.jcr.davex.impl.servlets.SlingDavExServlet
    depends_on:
      author-right:
        condition: service_healthy
    networks:
      - default
      - author-network

  traefik:
    image: traefik
    environment:
      - TZ=Australia/Sydney
    security_opt:
      - no-new-privileges:true
    restart: "always"
    command:
      - "--log.level=ERROR"
      - "--accesslog=true"
      - "--api.insecure=true" # Don't do that in production!
      - "--api.dashboard=true" # Don't do that in production!
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--global.sendAnonymousUsage=true"


      # Entrypoints for HTTP, HTTPS, and NX (TCP + UDP)
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      # - "--entrypoints.web.http.redirections.entryPoint.permanent=true"

      # Manual keys
      - "--providers.file.directory=/etc/traefik/dynamic_conf"
      - "--providers.file.watch=true"

    labels:
      traefik.frontend.priority: 1
      traefik.enable: true
      traefik.http.routers.dashboard.rule: "Host(`traefik.localhost`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      traefik.http.routers.dashboard.entrypoints: websecure
      traefik.http.routers.dashboard.tls: true
      traefik.http.routers.dashboard.service: api@internal

    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Persist certificates, so we can restart as often as needed
      - ./services/traefik/certs:/letsencrypt
      - ./services/traefik/config/dynamic:/etc/traefik/dynamic_conf/conf.yml:ro

    depends_on:
      - createcert
      - createcertpkcs12

    networks:
      - seleniumgrid
      - author-network
      - publish-network
      - dispatcher-network
      - default
      - internal

  createcert:
    image: brunopadz/mkcert-docker
    environment:
      - TZ=Australia/Sydney
    working_dir: /root/.local/share/mkcert
    command:
      - /bin/sh
      - -c
      - "test ! -f mkcert.key && mkcert -install && mkcert -key-file mkcert.key -cert-file mkcert.pem -client author.localhost publish.localhost dispatcher.localhost localhost 127.0.0.1 ::1 author-left.localhost author-right.localhost"
    volumes:
      - ./services/traefik/certs:/root/.local/share/mkcert

  createcertpkcs12:
    image: frapsoft/openssl
    environment:
      - TZ=Australia/Sydney
    working_dir: /export
    entrypoint: ""
    command:
      - /bin/ash
      - -c
      - "test ! -f mkcert.pfx && openssl pkcs12 -export -out mkcert.pfx -in mkcert.pem -inkey mkcert.key -certfile rootCA.pem -passout pass:123"
    depends_on:
      - createcert
    volumes:
      - ./services/traefik/certs:/export

networks:
  internal:
  seleniumgrid:
  author-network:
  publish-network:
  dispatcher-network:

volumes:
  # shared volume for moving hmac key to aem instances
  author-data-key:
  author-data-datastore:
  author-left-data:
  author-left-data-blobids:
  author-left-data-datastore:
  author-left-data-index:
  author-left-data-segmentstore:
  author-right-data:
  author-right-data-blobids:
  author-right-data-datastore:
  author-right-data-index:
  author-right-data-segmentstore:
  publish-data:
  dispatcher-data:
